mysite/mysite/urls.py
import os
from django.contrib import admin
from django.urls import include, path
from django.conf.urls import url
from django.views.static import serve

# Up two folders to serve "site" content
BASE_DIR = os.path.dirname(os.path.dirname(os.path.abspath(__file__)))
SITE_ROOT = os.path.join(BASE_DIR, 'site')

urlpatterns = [
    # path('', include('pyecharts_demo.urls')),
    path('admin/', admin.site.urls),
    path('polls/', include('polls.urls')),
    path('shop/', include('shop.urls')),
    path('pyecharts_demo/', include('pyecharts_demo.urls')),
    url(r'^site/(?P<path>.*)$', serve,
        {'document_root': SITE_ROOT, 'show_indexes': True},
        name='site_path'),
]

mysite/polls/urls.py
from django.urls import path
from . import views

app_name = 'polls'
urlpatterns = [
    # ex: /polls/
    path('', views.IndexView.as_view(), name='index'),
    # ex: /polls/5/
    path('<int:pk>/', views.DetailView.as_view(), name='detail'),
    # ex: /polls/5/results/
    path('<int:pk>/results/', views.ResultsView.as_view(), name='results'),
    # ex: /polls/5/vote/
    path('<int:question_id>/vote/', views.vote, name='vote'),
]

mysite/pyecharts_demo/urls.py
# from django.conf.urls import url
from django.urls import path

from . import views

urlpatterns = [
    # url(r'^$', views.index, name='index'),
    path('', views.index, name='index'),
]

mysite/shop/urls.py
from django.urls import path
from . import views


app_name = 'shop'
urlpatterns = [
    path('', views.IndexView.as_view(), name='index'),
    path('<str:name>', views.detail, name='detail'),
]

mysite/polls/models.py
import datetime
from django.db import models
from django.utils import timezone


# Create your models here.
class Question(models.Model):
    question_text = models.CharField(max_length=200)
    pub_date = models.DateTimeField('date published')

    def __str__(self):
        return self.question_text

    def was_published_recently(self):
        return self.pub_date >= timezone.now() - datetime.timedelta(days=1)


class Choice(models.Model):
    question = models.ForeignKey(Question, on_delete=models.CASCADE)
    choice_text = models.CharField(max_length=200)
    votes = models.IntegerField(default=0)

    def __str__(self):
        return self.choice_text

mysite/pyecharts_demo/models.py
from django.db import models

# Create your models here.

mysite/shop/models.py
from django.db import models

# Create your models here.

mysite/shop/forms.py
from audioop import maxpp
from email.policy import default
from django import forms


class DetailForm(forms.Form):
    pieces = forms.IntegerField(label='数量')

mysite/polls/views.py
from django.http import HttpResponse, HttpResponseRedirect
from django.shortcuts import get_object_or_404, render
from django.urls import reverse
from django.views import generic

from .models import Question, Choice


class IndexView(generic.ListView):
    template_name = 'polls/index.html'
    context_object_name = 'latest_question_list'

    def get_queryset(self):
        return Question.objects.order_by('-pub_date')[:5]


class DetailView(generic.DetailView):
    model = Question
    template_name = 'polls/detail.html'


class ResultsView(generic.DetailView):
    model = Question
    template_name = 'polls/results.html'


def vote(request, question_id):
    question = get_object_or_404(Question, pk=question_id)
    try:
        selected_choice = question.choice_set.get(pk=request.POST['choice'])
    except (KeyError, Choice.DoesNotExist):
        # Redisplay the question voting form.
        return render(request, 'polls/detail.html', {
            'question': question,
            'error_message': "You didn't select a choice.",
        })
    else:
        selected_choice.votes += 1
        selected_choice.save()
        # Always return an HttpResponseRedirect after successfully dealing
        # with POST data. This prevents data from being posted twice if a
        # user hits the Back button.
        return HttpResponseRedirect(reverse('polls:results', args=(question.id,)))

mysite/pyecharts_demo/views.py
from jinja2 import Environment, FileSystemLoader
from pyecharts.globals import CurrentConfig
from django.http import HttpResponse
from django.shortcuts import render

CurrentConfig.GLOBAL_ENV = Environment(loader=FileSystemLoader("./pyecharts_demo/templates"))

from pyecharts import options as opts
from pyecharts.charts import Bar


def index(request):
    c = (
        Bar()
        .add_xaxis(["衬衫", "羊毛衫", "雪纺衫", "裤子", "高跟鞋", "袜子"])
        .add_yaxis("商家A", [5, 20, 36, 10, 75, 90])
        .add_yaxis("商家B", [15, 25, 16, 55, 48, 8])
        .set_global_opts(title_opts=opts.TitleOpts(title="Bar-基本示例", subtitle="我是副标题"))
    )
    return HttpResponse(c.render_embed())
    # c.render(path='pyecharts_demo/templates/pyecharts_demo/bar_chart.html')
    #
    # return render(request, 'pyecharts_demo/bar_chart.html')

mysite/shop/views.py
from django.http import HttpResponse
from django.shortcuts import render, redirect
from django.urls import reverse
from django.views import generic
from .forms import DetailForm
import pymongo
import re


myclient = pymongo.MongoClient("mongodb://localhost:27017/")
mydb = myclient["magic_shop"]
mycol = mydb["foods"]


# Create your views here.
class IndexView(generic.ListView):
    template_name = 'shop/index.html'
    context_object_name = 'product_list'

    def get_queryset(self):
        return mycol.find({},{"_id": 0})


def detail(request, name):
    price = mycol.find({'name':name},{'_id':0})[0]['price']

    if request.method == 'POST':
        form = DetailForm(request.POST)
        if form.is_valid:
            pieces = request.POST['pieces']
            total = int(re.findall('\d+', price)[0]) * int(pieces)
            total = '{}元'.format(total)
            context = {
                'form': form,
                'name': name,
                'pieces': pieces,
                'price': price,
                'total': total,
            }
            return render(request, 'shop/detail.html', context)
    else:
        form = DetailForm({'pieces': 1})
        context = {
                'form': form,
                'name': name,
                'price': price,
                'total': '',
            }
        return render(request, 'shop/detail.html', context)

mysite/polls/templates/polls/base.html
<!DOCTYPE html>
<html lang="en">
<head>
    <link rel="stylesheet" href="style.css">
    <title>{% block title %}My amazing site{% endblock %}</title>
    {% load static %}
    <link rel="stylesheet" type="text/css" href="{% static 'polls/base.css' %}">
</head>

<body>
    <div id="sidebar">
        {% block sidebar %}
        <ul>
            <li><a href="/">Home</a></li>
            <li><a href="/blog/">Blog</a></li>
        </ul>
        {% endblock %}
    </div>

    <div id="content">
        {% block content %}{% endblock %}
    </div>
</body>
</html>

mysite/polls/templates/polls/detail.html
{% extends './base.html' %}

{% block title %}{{ question.question_test }}{% endblock %}

{% block content %}
<form action="{% url 'polls:vote' question.id %}" method="post">
    {% csrf_token %}
    <fieldset>
        <legend><h1>{{ question.question_text }}</h1></legend>
        {% if error_message %}<p><strong>{{ error_message }}</strong></p>{% endif %}
        {% for choice in question.choice_set.all %}
        <input type="radio" name="choice" id="choice{{ forloop.counter }}" value="{{ choice.id }}">
        <label for="choice{{ forloop.counter }}">{{ choice.choice_text }}</label><br>
        {% endfor %}
    </fieldset>
    <input type="submit" value="Vote">
</form>
{% endblock %}

mysite/polls/templates/polls/index.html
{% extends './base.html' %}

{% block title %}{{ question.question_text }}{% endblock %}

{% block content %}
    <h1>这是一个投票</h1>

    <ul>
    {% for question in latest_question_list %}
        <li>
            <span><a href="{% url 'polls:detail' question.id %}">{{ question.question_text }}</a></span>
        </li>
    {% endfor %}
    </ul>
{% endblock %}

mysite/polls/templates/polls/results.html
{% extends './base.html' %}

{% block title %}{{ question.question_test }}{% endblock %}

{% block content %}
    <h1>{{ question.question_text }}</h1>

    <ul>
        {% for choice in question.choice_set.all %}
        <li>{{ choice.choice_text }} -- {{ choice.votes }} vote{{ choice.votes|pluralize }}</li>
        {% endfor %}
    </ul>

    <a href="{% url 'polls:detail' question.id %}">Vote again?</a>
{% endblock %}

mysite/pyecharts_demo/templates/components.html
{% import 'macro' as macro %}
<!DOCTYPE html>
<html>
<head>
    <meta charset="UTF-8">
    <title>{{ chart.page_title }}</title>
</head>
<body>

{{ macro.gen_components_content(chart) }}

</body>
</html>

mysite/pyecharts_demo/templates/nb_components.html
{% import 'macro' as macro %}

{% for chart in charts %}
    {{ macro.gen_components_content(chart) }}
{% endfor %}

mysite/pyecharts_demo/templates/nb_jupyter_globe.html
<script>
    require.config({
        paths: {
            {{ config_items | join(', ') }}
        }
    });
</script>

{% for chart in charts %}
    <div id="{{ chart.chart_id }}" style="width:{{ chart.width }}; height:{{ chart.height }};"></div>
{% endfor %}


<script>
    require([{{ libraries | join(', ') }}], function(echarts) {
    {% for c in charts %}
		var canvas_{{ c.chart_id }} = document.createElement('canvas');
        var mapChart_{{ c.chart_id }} = echarts.init(
	    canvas_{{ c.chart_id }}, '{{ c.theme }}', {width: 4096, height: 2048, renderer: '{{ c.renderer }}'});
        var mapOption_{{ c.chart_id }} = {{ c.json_contents }};
        mapChart_{{ c.chart_id }}.setOption(mapOption_{{ c.chart_id }});
    	var chart_{{ c.chart_id }} = echarts.init(
            document.getElementById('{{ c.chart_id }}'), '{{ c.theme }}', {renderer: '{{ c.renderer }}'});
        {% for js in c.js_functions.items %}
            {{ js }}
        {% endfor %}
	    var option_{{ c.chart_id }} = {
           "globe": {
           "show": true,
		   "baseTexture": mapChart_{{ c.chart_id }},
           shading: 'lambert',
            light: {
                ambient: {
                    intensity: 0.6
                },
                main: {
                    intensity: 0.2
                }
             }

		   }};
        chart_{{ c.chart_id }}.setOption(option_{{ c.chart_id }});
    {% endfor %}
    });
</script>

mysite/pyecharts_demo/templates/nb_jupyter_lab.html
{% import 'macro' as macro %}
<!DOCTYPE html>
<html>
<head>
    <meta charset="UTF-8">
</head>
<body>
{% for chart in charts %}
    {% if chart._component_type in ("table", "image") %}
        {{ macro.gen_components_content(chart) }}
    {% else %}
        {{ macro.render_chart_content(chart) }}
    {% endif %}
{% endfor %}
</body>
</html>

mysite/pyecharts_demo/templates/nb_jupyter_lab_tab.html
{% import 'macro' as macro %}
<!DOCTYPE html>
<html>
<head>
    <meta charset="UTF-8">
</head>
<body>
{{ macro.generate_tab_css() }}
{{ macro.display_tablinks(charts) }}

{% for chart in charts %}
    {% if chart._component_type in ("table", "image") %}
        {{ macro.gen_components_content(chart) }}
    {% else %}
        {{ macro.render_chart_content(chart) }}
    {% endif %}
{% endfor %}
{{ macro.switch_tabs() }}
</body>
</html>

mysite/pyecharts_demo/templates/nb_jupyter_notebook.html
{% import 'macro' as macro %}

<script>
    require.config({
        paths: {
            {{ config_items | join(', ') }}
        }
    });
</script>

{% for chart in charts %}
    {% if chart._component_type in ("table", "image") %}
        {{ macro.gen_components_content(chart) }}
    {% else %}
        <div id="{{ chart.chart_id }}" style="width:{{ chart.width }}; height:{{ chart.height }};"></div>
    {% endif %}
{% endfor %}

{{ macro.render_notebook_charts(charts, libraries) }}

mysite/pyecharts_demo/templates/nb_jupyter_notebook_tab.html
{% import 'macro' as macro %}

<script>
    require.config({
        paths: {
            {{ config_items | join(', ') }}
        }
    });
</script>

{{ macro.generate_tab_css() }}
{{ macro.display_tablinks(charts) }}

{% for chart in charts %}
    {% if chart._component_type in ("table", "image") %}
        {{ macro.gen_components_content(chart) }}
    {% else %}
        <div id="{{ chart.chart_id }}" class="chart-container" style="width:{{ chart.width }}; height:{{ chart.height }};"></div>
    {% endif %}
{% endfor %}

{{ macro.render_notebook_charts(charts, libraries) }}
{{ macro.switch_tabs() }}

mysite/pyecharts_demo/templates/nb_nteract.html
{% import 'macro' as macro %}
<!DOCTYPE html>
<html>
<head>
    <meta charset="UTF-8">
    {{ macro.render_chart_dependencies(chart) }}
</head>
<body>
    {% for c in chart %}
        {{ macro.render_chart_content(c) }}
    {% endfor %}
</body>
</html>

mysite/pyecharts_demo/templates/pyecharts_demo/bar_chart.html
<!DOCTYPE html>
<html>
<head>
    <meta charset="UTF-8">
    <title>Awesome-pyecharts</title>
    
        <script type="text/javascript" src="https://assets.pyecharts.org/assets/echarts.min.js"></script>
    
</head>
<body>
    <div id="2e35175181f94ce0a17bf6768bd1ee14" class="chart-container" style="width:900px; height:500px;"></div>
    <script>
        var chart_2e35175181f94ce0a17bf6768bd1ee14 = echarts.init(
            document.getElementById('2e35175181f94ce0a17bf6768bd1ee14'), 'white', {renderer: 'canvas'});
        
        var option_2e35175181f94ce0a17bf6768bd1ee14 = {
    "animation": true,
    "animationThreshold": 2000,
    "animationDuration": 1000,
    "animationEasing": "cubicOut",
    "animationDelay": 0,
    "animationDurationUpdate": 300,
    "animationEasingUpdate": "cubicOut",
    "animationDelayUpdate": 0,
    "color": [
        "#c23531",
        "#2f4554",
        "#61a0a8",
        "#d48265",
        "#749f83",
        "#ca8622",
        "#bda29a",
        "#6e7074",
        "#546570",
        "#c4ccd3",
        "#f05b72",
        "#ef5b9c",
        "#f47920",
        "#905a3d",
        "#fab27b",
        "#2a5caa",
        "#444693",
        "#726930",
        "#b2d235",
        "#6d8346",
        "#ac6767",
        "#1d953f",
        "#6950a1",
        "#918597"
    ],
    "series": [
        {
            "type": "bar",
            "name": "\u5546\u5bb6A",
            "legendHoverLink": true,
            "data": [
                5,
                20,
                36,
                10,
                75,
                90
            ],
            "showBackground": false,
            "barMinHeight": 0,
            "barCategoryGap": "20%",
            "barGap": "30%",
            "large": false,
            "largeThreshold": 400,
            "seriesLayoutBy": "column",
            "datasetIndex": 0,
            "clip": true,
            "zlevel": 0,
            "z": 2,
            "label": {
                "show": true,
                "position": "top",
                "margin": 8
            }
        },
        {
            "type": "bar",
            "name": "\u5546\u5bb6B",
            "legendHoverLink": true,
            "data": [
                15,
                25,
                16,
                55,
                48,
                8
            ],
            "showBackground": false,
            "barMinHeight": 0,
            "barCategoryGap": "20%",
            "barGap": "30%",
            "large": false,
            "largeThreshold": 400,
            "seriesLayoutBy": "column",
            "datasetIndex": 0,
            "clip": true,
            "zlevel": 0,
            "z": 2,
            "label": {
                "show": true,
                "position": "top",
                "margin": 8
            }
        }
    ],
    "legend": [
        {
            "data": [
                "\u5546\u5bb6A",
                "\u5546\u5bb6B"
            ],
            "selected": {
                "\u5546\u5bb6A": true,
                "\u5546\u5bb6B": true
            },
            "show": true,
            "padding": 5,
            "itemGap": 10,
            "itemWidth": 25,
            "itemHeight": 14
        }
    ],
    "tooltip": {
        "show": true,
        "trigger": "item",
        "triggerOn": "mousemove|click",
        "axisPointer": {
            "type": "line"
        },
        "showContent": true,
        "alwaysShowContent": false,
        "showDelay": 0,
        "hideDelay": 100,
        "textStyle": {
            "fontSize": 14
        },
        "borderWidth": 0,
        "padding": 5
    },
    "xAxis": [
        {
            "show": true,
            "scale": false,
            "nameLocation": "end",
            "nameGap": 15,
            "gridIndex": 0,
            "inverse": false,
            "offset": 0,
            "splitNumber": 5,
            "minInterval": 0,
            "splitLine": {
                "show": false,
                "lineStyle": {
                    "show": true,
                    "width": 1,
                    "opacity": 1,
                    "curveness": 0,
                    "type": "solid"
                }
            },
            "data": [
                "\u886c\u886b",
                "\u7f8a\u6bdb\u886b",
                "\u96ea\u7eba\u886b",
                "\u88e4\u5b50",
                "\u9ad8\u8ddf\u978b",
                "\u889c\u5b50"
            ]
        }
    ],
    "yAxis": [
        {
            "show": true,
            "scale": false,
            "nameLocation": "end",
            "nameGap": 15,
            "gridIndex": 0,
            "inverse": false,
            "offset": 0,
            "splitNumber": 5,
            "minInterval": 0,
            "splitLine": {
                "show": false,
                "lineStyle": {
                    "show": true,
                    "width": 1,
                    "opacity": 1,
                    "curveness": 0,
                    "type": "solid"
                }
            }
        }
    ],
    "title": [
        {
            "text": "Bar-\u57fa\u672c\u793a\u4f8b",
            "subtext": "\u6211\u662f\u526f\u6807\u9898",
            "padding": 5,
            "itemGap": 10
        }
    ]
};
        chart_2e35175181f94ce0a17bf6768bd1ee14.setOption(option_2e35175181f94ce0a17bf6768bd1ee14);
        
        
    </script>
</body>
</html>

mysite/pyecharts_demo/templates/simple_chart.html
{% import 'macro' as macro %}
<!DOCTYPE html>
<html>
<head>
    <meta charset="UTF-8">
    <title>{{ chart.page_title }}</title>
    {{ macro.render_chart_dependencies(chart) }}
</head>
<body>
    {{ macro.render_chart_content(chart) }}
</body>
</html>

mysite/pyecharts_demo/templates/simple_globe.html
{% import 'macro' as macro %}
<!DOCTYPE html>
<html>
<head>
    <meta charset="UTF-8">
    <title>{{ chart.page_title }}</title>
    {{ macro.render_chart_dependencies(chart) }}
</head>
<body>
    <div id="{{ chart.chart_id }}" style="width:{{ chart.width }}; height:{{ chart.height }};"></div>
    <script>
		var canvas_{{ chart.chart_id }} = document.createElement('canvas');
        var mapChart_{{ chart.chart_id }} = echarts.init(
		     canvas_{{ chart.chart_id }}, '{{ chart.theme }}', {width: 4096, height: 2048, renderer: '{{ chart.renderer }}'});
        {% for js in chart.js_functions.items %}
            {{ js }}
        {% endfor %}
        var mapOption_{{ chart.chart_id }} = {{ chart.json_contents }};
        mapChart_{{ chart.chart_id }}.setOption(mapOption_{{ chart.chart_id }});

		var chart_{{ chart.chart_id }} = echarts.init(
        document.getElementById('{{ chart.chart_id }}'), '{{ chart.theme }}', {renderer: '{{ chart.renderer }}'});
		var options_{{ chart.chart_id }} = {
           "globe": {
           "show": true,
		   "baseTexture": mapChart_{{ chart.chart_id }},
           shading: 'lambert',
            light: {
                ambient: {
                    intensity: 0.6
                },
                main: {
                    intensity: 0.2
                }
             }

		   }};
		chart_{{ chart.chart_id }}.setOption(options_{{ chart.chart_id }});
    </script>
</body>
</html>

mysite/pyecharts_demo/templates/simple_page.html
{% import 'macro' as macro %}
<!DOCTYPE html>
<html>
<head>
    <meta charset="UTF-8">
    <title>{{ chart.page_title }}</title>
    {{ macro.render_chart_dependencies(chart) }}
    {{ macro.render_chart_css(chart) }}
</head>
<body>
    <style>.box { {{ chart.layout }} }; </style>
    {% if chart.download_button %}
        <button onclick="downloadCfg()">Save Config</button>
    {% endif %}
    <div class="box">
        {% for c in chart %}
            {% if c._component_type in ("table", "image") %}
                {{ macro.gen_components_content(c) }}
            {% else %}
                {{ macro.render_chart_content(c) }}
            {% endif %}
            {% for _ in range(chart.page_interval) %}<br/>{% endfor %}
        {% endfor %}
    </div>
    <script>
        {% for js in chart.js_functions.items %}
            {{ js }}
        {% endfor %}
    </script>
</body>
</html>

mysite/pyecharts_demo/templates/simple_tab.html
{% import 'macro' as macro %}
<!DOCTYPE html>
<html>
<head>
    <meta charset="UTF-8">
    <title>{{ chart.page_title }}</title>
    {{ macro.render_chart_dependencies(chart) }}
    {{ macro.render_chart_css(chart) }}
</head>
<body>
    {{ macro.generate_tab_css() }}
    {{ macro.display_tablinks(chart) }}

    <div class="box">
        {% for c in chart %}
            {% if c._component_type in ("table", "image") %}
                {{ macro.gen_components_content(c) }}
            {% else %}
                {{ macro.render_chart_content(c) }}
            {% endif %}
        {% endfor %}
    </div>

    <script>
        {% for js in chart.js_functions.items %}
            {{ js }}
        {% endfor %}
    </script>
    {{ macro.switch_tabs() }}
</body>
</html>

mysite/shop/templates/shop/base.html
{# Load the tag library #}
{% load bootstrap5 %}

{# Load CSS and JavaScript #}
{% bootstrap_css %}
{% bootstrap_javascript %}


<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Magic Shop</title>
    {% load static %}
    <link href="{% static 'fontawesomefree/css/all.min.css' %}" rel="stylesheet" type="text/css">
    <script src="{% static 'fontawesomefree/js/all.min.js' %}"></script>
</head>
<body>
    <header class="d-flex flex-wrap justify-content-center py-3 mb-4 border-bottom">
        <a href="/" class="d-flex align-items-center mb-3 mb-md-0 me-md-auto text-dark text-decoration-none">
        <svg class="bi me-2" width="40" height="32"><use xlink:href="#bootstrap"/></svg>
        <span class="fs-4 text-primary"><i class="fa-solid fa-shop"></i>  Elaine's Shop</span>
        </a>

        <ul class="nav nav-pills">
        <li class="nav-item"><a href="#" class="nav-link active" aria-current="page">Home</a></li>
        <li class="nav-item"><a href="#" class="nav-link">Features</a></li>
        <li class="nav-item"><a href="#" class="nav-link">Pricing</a></li>
        <li class="nav-item"><a href="#" class="nav-link">FAQs</a></li>
        <li class="nav-item"><a href="#" class="nav-link">About</a></li>
        </ul>
    </header>

    {% block content %}{% endblock %}

    <footer class="d-flex flex-wrap justify-content-between align-items-center py-3 my-4 border-top">
        <div class="col-md-4 d-flex align-items-center">
          <a href="/" class="mb-3 me-2 mb-md-0 text-muted text-decoration-none lh-1">
            <svg class="bi" width="30" height="24"><use xlink:href="#bootstrap"/></svg>
          </a>
          <span class="mb-3 mb-md-0 text-muted">&copy; Elaine's shop</span>
        </div>
    
        <ul class="nav me-5 col-md-4 justify-content-end list-unstyled d-flex">
          <li class="ms-3"><a class="text-muted" href="#"><i class="fa-brands fa-weixin"></i></a></li>
          <li class="ms-3"><a class="text-muted" href="#"><i class="fa-brands fa-weibo"></i></a></li>
          <li class="ms-3"><a class="text-muted" href="#"><i class="fa-brands fa-tencent-weibo"></i></a></li>
        </ul>
      </footer>
</body>
</html>

mysite/shop/templates/shop/detail.html
{% extends './base.html' %}

{% block content %}

<div class="container">
    <div class="row">
        <div class="col-6">
            <ul class="my-2">
                <li class="my-2">商品名称： {{ name }}</li>
                <li class="my-2">商品单价： {{ price }}</li>
                <li class="my-2">总计： {{ total }}</li>
                <form  class="my-2" action="" method="post">
                    {% csrf_token %}
                    {{ form.as_ul }}
                    <br>
                    <input class="btn btn-primary" type="submit" value="确定">
                    <a class="btn btn-danger" href="{% url 'shop:index' %}">返回</a>
                </form>
            </ul>
        </div>
    </div>
</div>

{% endblock %}

mysite/shop/templates/shop/index.html
{% extends './base.html' %}

{% block content %}

    <div class="container mx-5 px-5 text-primary text-center ">
        <h1>欢迎来到Elaine的魔法商店！</h1>
    </div>

    <div class="container mt-3">
        <div class="row">
            {% for product in product_list %}
            <div class="col-lg-3 col-md-6 col-sm-12">
                <div class="card" style="width: 18rem;">
                    {% load static %}
                    <img src="../../static/shop/images/food_{{ forloop.counter }}.jpg" class="card-img-top" alt="...">
                    <div class="card-body">
                      <h5 class="card-title">{{ product.name }}</h5>
                      <p class="card-text">{{ product.price }}<br>网友评分：{{ product.grade }}</p>
                      <a href="#" class="btn btn-primary">收藏 <i class="fa-solid fa-thumbs-up"></i></a>
                      <a href="{% url 'shop:detail' product.name %}" class="btn btn-primary">购买 <i class="fa-solid fa-cart-shopping"></i>"</a>
                    </div>
                </div>
            </div>
            {% endfor %}
        </div>
    </div>

{% endblock %}

mysite/shop/templates/shop/result.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Document</title>
</head>
<body>
    <p>{{ contents.p_name }}</p>
    <p>{{ contents.p_vote }}</p>
    
</body>
</html>